services:
  postgresql_database:
    build:
      context: ./postgresql_database
      dockerfile: dockerfile
    image: edgedashboard_v4/postgresql_database:0.0.1
    container_name: edgedashboard_v4_postgresql_database
    mem_limit: 256m
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    ports:
      - "35010:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - data-service-network

  data_inserter_service:
    build:
      context: ./data_inserter_service
      dockerfile: dockerfile
    image: edgedashboard_v4/data_inserter_service:0.0.1
    container_name: edgedashboard_v4_data_inserter_service
    mem_limit: 256m
    restart: unless-stopped
    depends_on:
      postgresql_database:
        condition: service_healthy
    environment:
      - DB_HOST=postgresql_database
      - DB_PORT=5432
      - DB_NAME=postgres_db
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
    networks:
      - data-service-network

networks:
  data-service-network:
    name: data-service-network
    driver: bridge

volumes:
  pg_data: